### ISSUE TITLE
Im from the vid!!! and i get an error ;(

### ISSUE THREAD

**Issue by ghost** [rawheel/Google-Meet-Bot-to-attend-meetings#1]
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
Please help me ;(!

**Comment by rawheel** [comment]
there are two solutions to this issue:
1) goto Gmail settings and allow access to use Gmail account there are some securities that you have to allow.
2) use a different email address, other than the @gmail domain.
